<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Brand>
 */
class BrandFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $name = $this->faker->unique()->company;

        return [
            'name' => $name.rand(1, 100000),
            // The slug is automatically generated by the Brand model's boot method.
            // 'slug' => Str::slug($name),
            'logo' => null, // We can leave the logo null for testing purposes.
            'status' => 1,  // Default to an active status.
        ];
    }
}
