<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Category>
 */
class CategoryFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $name = $this->faker->unique()->word;

        return [
            'name' => ucfirst($name).rand(1, 100000),
            // The slug is automatically generated by the Category model's boot method,
            // so we don't need to define it here.
            // 'slug' => Str::slug($name),
            'image' => null, // We can leave the image null for testing purposes.
            'status' => 1,   // Default to an active status.
        ];
    }
}
